const ACTION_MENU = 201;
const IMAGE_DROPZONE_LOADING_COVER = 200;
const TEXT_POPOVER = 10;
const VIDEO_TEXT_COVER = 1;

export const Z_INDEX = {
  ACTION_MENU,
  IMAGE_DROPZONE_LOADING_COVER,
  TEXT_POPOVER,
  VIDEO_TEXT_COVER,
};
