import type { SerializedNodes } from '@craftjs/core';

import { EMPTY_CONTENT_JSON_BODY } from '../utils';

const ONE_TEXT = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['A9QR9ep0JV'],
    linkedNodes: {},
  },
  A9QR9ep0JV: {
    type: {
      resolvedName: 'OneColumnText',
    },
    isCanvas: false,
    props: {
      scrollWhenCreated: false,
    },
    displayName: 't$',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'one-column-grid': 'QOjZr5R8vI',
    },
  },
  QOjZr5R8vI: {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'one-column-grid',
    },
    displayName: 'div',
    custom: {},
    parent: 'A9QR9ep0JV',
    hidden: false,
    nodes: ['6pMMKkFreI'],
    linkedNodes: {},
  },
  '6pMMKkFreI': {
    type: {
      resolvedName: 'Box',
    },
    isCanvas: false,
    props: {},
    displayName: 'tP',
    custom: {},
    parent: 'QOjZr5R8vI',
    hidden: false,
    nodes: [],
    linkedNodes: {
      box: 'n22ZNCku0M',
    },
  },
  n22ZNCku0M: {
    type: 'div',
    isCanvas: false,
    props: {},
    displayName: 'div',
    custom: {},
    parent: '6pMMKkFreI',
    hidden: false,
    nodes: ['4coKO5NzOo'],
    linkedNodes: {},
  },
  '4coKO5NzOo': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'box__children-wrapper',
    },
    displayName: 'div',
    custom: {},
    parent: 'n22ZNCku0M',
    hidden: false,
    nodes: ['bc_Jb-Ryxd'],
    linkedNodes: {},
  },
  'bc_Jb-Ryxd': {
    type: {
      resolvedName: 'Text',
    },
    isCanvas: false,
    props: {
      focusWhenCreated: false,
      content: '<p></p>',
    },
    displayName: 'Text',
    custom: {},
    parent: '4coKO5NzOo',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};

const ONE_INFO_BOX = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['bKPWoj68DQ'],
    linkedNodes: {},
  },
  bKPWoj68DQ: {
    type: {
      resolvedName: 'OneColumnText',
    },
    isCanvas: false,
    props: {
      scrollWhenCreated: false,
    },
    displayName: 'OneColumnText',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'one-column-grid': 'AG-752YCk5',
    },
  },
  'AG-752YCk5': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'one-column-grid',
    },
    displayName: 'div',
    custom: {},
    parent: 'bKPWoj68DQ',
    hidden: false,
    nodes: ['QHUae7v0DA'],
    linkedNodes: {},
  },
  QHUae7v0DA: {
    type: {
      resolvedName: 'Box',
    },
    isCanvas: false,
    props: {},
    displayName: 'Box',
    custom: {},
    parent: 'AG-752YCk5',
    hidden: false,
    nodes: [],
    linkedNodes: {
      box: 'jT86rGYwY_',
    },
  },
  jT86rGYwY_: {
    type: 'div',
    isCanvas: false,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'QHUae7v0DA',
    hidden: false,
    nodes: ['C-rwGUHTKz'],
    linkedNodes: {},
  },
  'C-rwGUHTKz': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'box__children-wrapper',
    },
    displayName: 'div',
    custom: {},
    parent: 'jT86rGYwY_',
    hidden: false,
    nodes: ['25JYpkjbIM'],
    linkedNodes: {},
  },
  '25JYpkjbIM': {
    type: {
      resolvedName: 'InfoBox',
    },
    isCanvas: false,
    props: {
      hasIcon: true,
      color: 'gray',
      value: '',
      focusWhenCreated: false,
    },
    displayName: 'InfoBox',
    custom: {},
    parent: 'C-rwGUHTKz',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};

const ONE_IMAGE = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['bKPWoj68DQ'],
    linkedNodes: {},
  },
  bKPWoj68DQ: {
    type: {
      resolvedName: 'OneColumnText',
    },
    isCanvas: false,
    props: {
      scrollWhenCreated: false,
    },
    displayName: 'OneColumnText',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'one-column-grid': 'AG-752YCk5',
    },
  },
  'AG-752YCk5': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'one-column-grid',
    },
    displayName: 'div',
    custom: {},
    parent: 'bKPWoj68DQ',
    hidden: false,
    nodes: ['QHUae7v0DA'],
    linkedNodes: {},
  },
  QHUae7v0DA: {
    type: {
      resolvedName: 'Box',
    },
    isCanvas: false,
    props: {},
    displayName: 'Box',
    custom: {},
    parent: 'AG-752YCk5',
    hidden: false,
    nodes: [],
    linkedNodes: {
      box: 'jT86rGYwY_',
    },
  },
  jT86rGYwY_: {
    type: 'div',
    isCanvas: false,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'QHUae7v0DA',
    hidden: false,
    nodes: ['C-rwGUHTKz'],
    linkedNodes: {},
  },
  'C-rwGUHTKz': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'box__children-wrapper',
    },
    displayName: 'div',
    custom: {},
    parent: 'jT86rGYwY_',
    hidden: false,
    nodes: ['dMX_DepEJM'],
    linkedNodes: {},
  },
  dMX_DepEJM: {
    type: {
      resolvedName: 'ImageText',
    },
    isCanvas: false,
    props: {},
    displayName: 'ImageText',
    custom: {},
    parent: 'C-rwGUHTKz',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};

const ONE_VIDEO = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['bKPWoj68DQ'],
    linkedNodes: {},
  },
  bKPWoj68DQ: {
    type: {
      resolvedName: 'OneColumnText',
    },
    isCanvas: false,
    props: {
      scrollWhenCreated: false,
    },
    displayName: 'OneColumnText',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'one-column-grid': 'AG-752YCk5',
    },
  },
  'AG-752YCk5': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'one-column-grid',
    },
    displayName: 'div',
    custom: {},
    parent: 'bKPWoj68DQ',
    hidden: false,
    nodes: ['QHUae7v0DA'],
    linkedNodes: {},
  },
  QHUae7v0DA: {
    type: {
      resolvedName: 'Box',
    },
    isCanvas: false,
    props: {},
    displayName: 'Box',
    custom: {},
    parent: 'AG-752YCk5',
    hidden: false,
    nodes: [],
    linkedNodes: {
      box: 'jT86rGYwY_',
    },
  },
  jT86rGYwY_: {
    type: 'div',
    isCanvas: false,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'QHUae7v0DA',
    hidden: false,
    nodes: ['C-rwGUHTKz'],
    linkedNodes: {},
  },
  'C-rwGUHTKz': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'box__children-wrapper',
    },
    displayName: 'div',
    custom: {},
    parent: 'jT86rGYwY_',
    hidden: false,
    nodes: ['7I6aMUqPhu'],
    linkedNodes: {},
  },
  '7I6aMUqPhu': {
    type: {
      resolvedName: 'VideoText',
    },
    isCanvas: false,
    props: {},
    displayName: 'VideoText',
    custom: {},
    parent: 'C-rwGUHTKz',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};

const TWO_BLOCK = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['bKPWoj68DQ', '4gAmOqMrGC'],
    linkedNodes: {},
  },
  bKPWoj68DQ: {
    type: {
      resolvedName: 'OneColumnText',
    },
    isCanvas: false,
    props: {
      scrollWhenCreated: false,
    },
    displayName: 'OneColumnText',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'one-column-grid': 'AG-752YCk5',
    },
  },
  'AG-752YCk5': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'one-column-grid',
    },
    displayName: 'div',
    custom: {},
    parent: 'bKPWoj68DQ',
    hidden: false,
    nodes: ['QHUae7v0DA'],
    linkedNodes: {},
  },
  QHUae7v0DA: {
    type: {
      resolvedName: 'Box',
    },
    isCanvas: false,
    props: {},
    displayName: 'Box',
    custom: {},
    parent: 'AG-752YCk5',
    hidden: false,
    nodes: [],
    linkedNodes: {
      box: 'jT86rGYwY_',
    },
  },
  jT86rGYwY_: {
    type: 'div',
    isCanvas: false,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'QHUae7v0DA',
    hidden: false,
    nodes: ['C-rwGUHTKz'],
    linkedNodes: {},
  },
  'C-rwGUHTKz': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'box__children-wrapper',
    },
    displayName: 'div',
    custom: {},
    parent: 'jT86rGYwY_',
    hidden: false,
    nodes: ['M6XTasmICG'],
    linkedNodes: {},
  },
  M6XTasmICG: {
    type: {
      resolvedName: 'Text',
    },
    isCanvas: false,
    props: {
      focusWhenCreated: false,
    },
    displayName: 'Text',
    custom: {},
    parent: 'C-rwGUHTKz',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  '4gAmOqMrGC': {
    type: {
      resolvedName: 'TwoColumnGrid',
    },
    isCanvas: false,
    props: {
      scrollWhenCreated: false,
    },
    displayName: 'TwoColumnGrid',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'two-column-grid': 'N5I4EIz8ek',
    },
  },
  N5I4EIz8ek: {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'two-column-grid',
    },
    displayName: 'div',
    custom: {},
    parent: '4gAmOqMrGC',
    hidden: false,
    nodes: ['ReJvOYCfCX', 'bA6UGIyOEG'],
    linkedNodes: {},
  },
  ReJvOYCfCX: {
    type: {
      resolvedName: 'Box',
    },
    isCanvas: false,
    props: {},
    displayName: 'Box',
    custom: {},
    parent: 'N5I4EIz8ek',
    hidden: false,
    nodes: [],
    linkedNodes: {
      box: 'kTBph6fC2T',
    },
  },
  bA6UGIyOEG: {
    type: {
      resolvedName: 'Box',
    },
    isCanvas: false,
    props: {},
    displayName: 'Box',
    custom: {},
    parent: 'N5I4EIz8ek',
    hidden: false,
    nodes: [],
    linkedNodes: {
      box: '2D63_KmIyE',
    },
  },
  kTBph6fC2T: {
    type: 'div',
    isCanvas: false,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'ReJvOYCfCX',
    hidden: false,
    nodes: ['dnLfsD7fwQ'],
    linkedNodes: {},
  },
  dnLfsD7fwQ: {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'box__children-wrapper',
    },
    displayName: 'div',
    custom: {},
    parent: 'kTBph6fC2T',
    hidden: false,
    nodes: ['pdMM9VkXCZ'],
    linkedNodes: {},
  },
  pdMM9VkXCZ: {
    type: {
      resolvedName: 'AddElementBox',
    },
    isCanvas: false,
    props: {},
    displayName: 'AddElementBox',
    custom: {},
    parent: 'dnLfsD7fwQ',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  '2D63_KmIyE': {
    type: 'div',
    isCanvas: false,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'bA6UGIyOEG',
    hidden: false,
    nodes: ['gsa_SYW0S5'],
    linkedNodes: {},
  },
  gsa_SYW0S5: {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'box__children-wrapper',
    },
    displayName: 'div',
    custom: {},
    parent: '2D63_KmIyE',
    hidden: false,
    nodes: ['jaU-TvZg99'],
    linkedNodes: {},
  },
  'jaU-TvZg99': {
    type: {
      resolvedName: 'AddElementBox',
    },
    isCanvas: false,
    props: {},
    displayName: 'AddElementBox',
    custom: {},
    parent: 'gsa_SYW0S5',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};

const THREE_BLOCK = {
  ROOT: {
    type: 'div',
    isCanvas: true,
    props: {},
    displayName: 'div',
    custom: {},
    hidden: false,
    nodes: ['bKPWoj68DQ', '4gAmOqMrGC', 'QStz-YfsgS'],
    linkedNodes: {},
  },
  bKPWoj68DQ: {
    type: {
      resolvedName: 'OneColumnText',
    },
    isCanvas: false,
    props: {
      scrollWhenCreated: false,
    },
    displayName: 'OneColumnText',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'one-column-grid': 'AG-752YCk5',
    },
  },
  'AG-752YCk5': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'one-column-grid',
    },
    displayName: 'div',
    custom: {},
    parent: 'bKPWoj68DQ',
    hidden: false,
    nodes: ['QHUae7v0DA'],
    linkedNodes: {},
  },
  QHUae7v0DA: {
    type: {
      resolvedName: 'Box',
    },
    isCanvas: false,
    props: {},
    displayName: 'Box',
    custom: {},
    parent: 'AG-752YCk5',
    hidden: false,
    nodes: [],
    linkedNodes: {
      box: 'jT86rGYwY_',
    },
  },
  jT86rGYwY_: {
    type: 'div',
    isCanvas: false,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'QHUae7v0DA',
    hidden: false,
    nodes: ['C-rwGUHTKz'],
    linkedNodes: {},
  },
  'C-rwGUHTKz': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'box__children-wrapper',
    },
    displayName: 'div',
    custom: {},
    parent: 'jT86rGYwY_',
    hidden: false,
    nodes: ['M6XTasmICG'],
    linkedNodes: {},
  },
  M6XTasmICG: {
    type: {
      resolvedName: 'Text',
    },
    isCanvas: false,
    props: {
      focusWhenCreated: false,
    },
    displayName: 'Text',
    custom: {},
    parent: 'C-rwGUHTKz',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  '4gAmOqMrGC': {
    type: {
      resolvedName: 'TwoColumnGrid',
    },
    isCanvas: false,
    props: {
      scrollWhenCreated: false,
    },
    displayName: 'TwoColumnGrid',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'two-column-grid': 'N5I4EIz8ek',
    },
  },
  N5I4EIz8ek: {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'two-column-grid',
    },
    displayName: 'div',
    custom: {},
    parent: '4gAmOqMrGC',
    hidden: false,
    nodes: ['ReJvOYCfCX', 'bA6UGIyOEG'],
    linkedNodes: {},
  },
  ReJvOYCfCX: {
    type: {
      resolvedName: 'Box',
    },
    isCanvas: false,
    props: {},
    displayName: 'Box',
    custom: {},
    parent: 'N5I4EIz8ek',
    hidden: false,
    nodes: [],
    linkedNodes: {
      box: 'kTBph6fC2T',
    },
  },
  bA6UGIyOEG: {
    type: {
      resolvedName: 'Box',
    },
    isCanvas: false,
    props: {},
    displayName: 'Box',
    custom: {},
    parent: 'N5I4EIz8ek',
    hidden: false,
    nodes: [],
    linkedNodes: {
      box: '2D63_KmIyE',
    },
  },
  kTBph6fC2T: {
    type: 'div',
    isCanvas: false,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'ReJvOYCfCX',
    hidden: false,
    nodes: ['dnLfsD7fwQ'],
    linkedNodes: {},
  },
  dnLfsD7fwQ: {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'box__children-wrapper',
    },
    displayName: 'div',
    custom: {},
    parent: 'kTBph6fC2T',
    hidden: false,
    nodes: ['pdMM9VkXCZ'],
    linkedNodes: {},
  },
  pdMM9VkXCZ: {
    type: {
      resolvedName: 'AddElementBox',
    },
    isCanvas: false,
    props: {},
    displayName: 'AddElementBox',
    custom: {},
    parent: 'dnLfsD7fwQ',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  '2D63_KmIyE': {
    type: 'div',
    isCanvas: false,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'bA6UGIyOEG',
    hidden: false,
    nodes: ['gsa_SYW0S5'],
    linkedNodes: {},
  },
  gsa_SYW0S5: {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'box__children-wrapper',
    },
    displayName: 'div',
    custom: {},
    parent: '2D63_KmIyE',
    hidden: false,
    nodes: ['jaU-TvZg99'],
    linkedNodes: {},
  },
  'jaU-TvZg99': {
    type: {
      resolvedName: 'AddElementBox',
    },
    isCanvas: false,
    props: {},
    displayName: 'AddElementBox',
    custom: {},
    parent: 'gsa_SYW0S5',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  'QStz-YfsgS': {
    type: {
      resolvedName: 'OneColumnText',
    },
    isCanvas: false,
    props: {
      scrollWhenCreated: false,
    },
    displayName: 'OneColumnText',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {
      'one-column-grid': 'W26-FZq9k6',
    },
  },
  'W26-FZq9k6': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'one-column-grid',
    },
    displayName: 'div',
    custom: {},
    parent: 'QStz-YfsgS',
    hidden: false,
    nodes: ['TbKq29XVYL'],
    linkedNodes: {},
  },
  TbKq29XVYL: {
    type: {
      resolvedName: 'Box',
    },
    isCanvas: false,
    props: {},
    displayName: 'Box',
    custom: {},
    parent: 'W26-FZq9k6',
    hidden: false,
    nodes: [],
    linkedNodes: {
      box: 'dIrVd8eTN3',
    },
  },
  dIrVd8eTN3: {
    type: 'div',
    isCanvas: false,
    props: {},
    displayName: 'div',
    custom: {},
    parent: 'TbKq29XVYL',
    hidden: false,
    nodes: ['RQZHAWb0-S'],
    linkedNodes: {},
  },
  'RQZHAWb0-S': {
    type: 'div',
    isCanvas: false,
    props: {
      className: 'box__children-wrapper',
    },
    displayName: 'div',
    custom: {},
    parent: 'dIrVd8eTN3',
    hidden: false,
    nodes: ['Mf-oTuCyD-'],
    linkedNodes: {},
  },
  'Mf-oTuCyD-': {
    type: {
      resolvedName: 'AddElementBox',
    },
    isCanvas: false,
    props: {},
    displayName: 'AddElementBox',
    custom: {},
    parent: 'RQZHAWb0-S',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};

export const testFixtures = {
  EMPTY_CONTENT: EMPTY_CONTENT_JSON_BODY,
  ONE_TEXT,
  ONE_INFO_BOX,
  ONE_IMAGE,
  ONE_VIDEO,
  TWO_BLOCK,
  THREE_BLOCK,
} as unknown as { [key: string]: SerializedNodes };
